### ISSUE TITLE
Masks inside of variants do not render correctly

### ISSUE THREAD

**Issue by HooHaa-code** [google/automotive-design-compose#905]
Having a mask inside of a variant causes the object to render incorrectly:

### Rendered
![image](https://github.com/google/automotive-design-compose/assets/64603080/b155faa7-d1bc-4297-b769-d457259d9fdf)

### Expected
![image](https://github.com/google/automotive-design-compose/assets/64603080/d4bb124f-3876-4488-96ed-f6fcb9cd65a4)

example project is attached
[Ex4Google-variant-mask.zip](https://github.com/google/automotive-design-compose/files/14808046/Ex4Google-variant-mask.zip)

**Comment by iamralpht** [comment]
@HooHaa-code is this with 0.22-rc or 0.21? I'm wondering if the layout changes improve matters.

Alternatively, there's a new implementation of masking in `main` if you enable "SQUOOSH" here: https://github.com/google/automotive-design-compose/blob/3d8f2e9f5e39ff32476e6d3ee3e576e9e612b339/designcompose/src/main/java/com/android/designcompose/DesignView.kt#L971 -- this will break all kinds of other things (lists and grids, content substitution, etc) but it improves some rendering fidelity, e.g.: multiple masks on a single object should work, some basic animations are present, etc.

**Comment by HooHaa-code** [comment]
I have '+' set for design compose in libs.versions.toml.  So it should be 0.25.0

**Comment by iamralpht** [comment]
Ok, I am not sure if that would have gotten you the 0.25.0-rc release (@timothyfroehlich knows how these rules work). We just pushed 0.25.0 to Maven (about 30 minutes ago) so updating dependencies now should definitely pull it in.

**Comment by HooHaa-code** [comment]
I guess I assumed that when a release it git hub is made that we would get it though maven.  I was wrong in that assumption.  I just did a sync and say the 0.25.0 artifacts get pulled in.

The behavior is still the same
